### ISSUE TITLE
Flujo inicial de interesados

### ISSUE THREAD

**Issue by teanocrata** [ilice/OSCapi#98]
Embudo para los interesados, sería muy interesante poder hablar con ellos pero ¿cómo?, alguien que busca ¿por qué querría ponerse en contacto con nosotros? ¿Quienes buscan?
- [ ] Buscador #89 
- [ ] Descripcción de la persona, quien, por qué, cómo
- [ ] Contacto, correos, etc. Pensar cómo va a ser la interacción
- [ ] ¿Cómo lo vamos a medir?
